### ISSUE TITLE
Add profile and analyze samples

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp-spanner#960] opened 2019-10-16 02:56 UTC
Add samples for
- ProfileQuery
- ProfileDml
- AnalyzeSql

**Comment by devjgm** [comment] 2019-11-26 14:58
I think this is now a dupe of #1112 #1113 #1114 , which are about adding integration tests for these functions. There are no official "samples" that are needed for these, so I think the integration tests are what was meant here.

**Closed by devjgm** 2019-11-26 14:58 UTC
Labels: type: feature request
