### ISSUE TITLE
[Flake]: ExecuteBatchDml fails with partial transaction?

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp-spanner#1156] opened 2019-12-17 14:00 UTC
One of the continuous builds failed with:

https://source.cloud.google.com/results/invocations/ee0d16df-cacd-4ae8-a844-f23a560bdd3a

The specific failure is here:

```
[ RUN      ] ClientIntegrationTest.ExecuteBatchDmlMany
google/cloud/spanner/integration_tests/client_integration_test.cc:742: Failure
Expected equality of these values:
  std::get<0>(*row)
    Which is: 100
  counter
    Which is: 0
[  FAILED  ] ClientIntegrationTest.ExecuteBatchDmlMany (42781 ms)
```

Some observations: that test was running for 42 seconds before failing, normally the whole testsuite takes less than 90 seconds, seems like there were some retries.

Second, the code that failed reads:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c87211607b75464f8e787d0017538da398ad4da7/google/cloud/spanner/integration_tests/client_integration_test.cc#L735-L746

That tells me that the first row committed to the table has `SingerId == 0`. The way these rows are committed is in two batches:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c87211607b75464f8e787d0017538da398ad4da7/google/cloud/spanner/integration_tests/client_integration_test.cc#L702-L714

The `left` batch contains rows with `SingerId` in the `[0, 100)` range, while the `right` batch contains the remaining rows:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/c87211607b75464f8e787d0017538da398ad4da7/google/cloud/spanner/integration_tests/client_integration_test.cc#L696-L697

Seems like only 1/2 of the transaction was committed, which is "not how transactions work".

**Comment by coryan** [comment] 2020-01-02 14:44
FWIW, I ran the test 3,000 times (3 copies running in parallel, each copy running the tests 1,000 times) 
 without being able to reproduce this problem.

**Comment by devjgm** [comment] 2020-01-14 16:35
Should we keep this open if we can't repro it?

**Comment by coryan** [comment] 2020-01-14 16:40
I cannot repro it, but I did not change anything that explains why it went away either.

I was thinking of closing all flakes after 90 days (or once a quarter, or as part of a Fix It), but I am open to another schedule, thoughts?

**Comment by devjgm** [comment] 2020-01-14 16:42
I like your suggestion of closing flakes that we can't repro after 90 days. That beats my shoot-from-the-hip policy.

**Comment by devjgm** [comment] 2020-03-16 19:43
It's been [90 days since Dec 17](https://www.convertunits.com/dates/90/daysfrom/Dec+17,+2019). This hasn't been reproduced. Closing.

**Closed by devjgm** 2020-03-16 19:43 UTC
Labels: api: spanner, priority: p2, type: bug
