### ISSUE TITLE
Does not build with bazel 1.0.0 on macOS

### ISSUE THREAD

**Issue by aryann** [googleapis/google-cloud-cpp-spanner#954] opened 2019-10-13 18:56 UTC
Error from issuing `bazel build ...` from the root dir:

```$ bazel build ...
INFO: Writing tracer profile to '/private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/command.profile.gz'
ERROR: /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/com_google_googleapis/BUILD.bazel:49:1: in srcs attribute of _generate_cc rule @com_google_googleapis//:_google_spanner_admin_instance_v1_spanner_instance_admin_grpc_codegen: '@com_google_googleapis//google/spanner/admin/instance/v1:spanner_admin_instance_proto' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/com_google_googleapis/BUILD.bazel:49:1
INFO: Call stack for the definition of repository 'boringssl' which is a http_archive (rule definition at /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/com_github_grpc_grpc/bazel/grpc_deps.bzl:110:9
 - /Users/aryann/Desktop/desktop/google-cloud-cpp-spanner/WORKSPACE:40:1
INFO: Call stack for the definition of repository 'remote_java_tools_darwin' which is a http_archive (rule definition at /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/bazel_tools/tools/build_defs/repo/utils.bzl:169:9
 - /DEFAULT.WORKSPACE.SUFFIX:280:1
INFO: Call stack for the definition of repository 'remotejdk11_macos' which is a http_archive (rule definition at /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/bazel_tools/tools/build_defs/repo/http.bzl:262:16):
 - /private/var/tmp/_bazel_aryann/fd253c9387e43bb0eed47e7cee48bd49/external/bazel_tools/tools/build_defs/repo/utils.bzl:169:9
 - /DEFAULT.WORKSPACE.SUFFIX:238:1
ERROR: Analysis of target '//google/cloud/spanner:spanner_client' failed; build aborted: Analysis of target '@com_google_googleapis//:_google_spanner_admin_instance_v1_spanner_instance_admin_grpc_codegen' failed; build aborted
INFO: Elapsed time: 20.966s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (44 packages loaded, 1962 targets configured)
```

OS: macOS Mojave version 10.14.6
Bazel: 1.0.0

**Comment by coryan** [comment] 2019-10-13 20:03
What version of `google-cloud-cpp-spanner` did you use?  Did it include #951 (merged two days ago)?

Did you try with `base build //google/cloud/...:all` ?  We probably should add a `.bazelignore` file to skip the `ci/` subdirectory, as it contains BUILD files only intended for testing.

**Comment by coryan** [comment] 2019-10-13 20:09
Oh, and for the record, I am trying to reproduce this myself... It is perfectly possible that macOS + b azel-1.0 is broken, we are testing with bazel-0.28.0 (and only test 1.0 on [Ubuntu:18.04](https://buildkite.com/bazel/github-dot-com-googleapis-google-cloud-cpp-spanner)).

**Comment by hcoona** [comment] 2019-10-14 10:18
Reproduce it with following error messages:

```
INFO: Writing tracer profile to '/private/var/tmp/_bazel_shuaiz/565f7084b4af1d230cb77eff5d4259c7/command.profile.gz'
INFO: Invocation ID: 80760d01-8018-44c6-87ea-f878a3263939
ERROR: /Users/shuaiz/GitEnlistments/one/codelab/grpc_greeter/proto/BUILD.bazel:5:1: in srcs attribute of _generate_cc rule //codelab/grpc_greeter/proto:_hello_cc_proto_grpc_codegen: '//codelab/grpc_greeter/proto:_hello_cc_proto_only' does not have mandatory providers: 'proto'. Since this rule was created by the macro 'cc_grpc_library', the error might have been caused by the macro implementation in /Users/shuaiz/GitEnlistments/one/codelab/grpc_greeter/proto/BUILD.bazel:5:1
ERROR: Analysis of target '//codelab/grpc_greeter/proto:_hello_cc_proto_grpc_codegen' failed; build aborted: Analysis of target '//codelab/grpc_greeter/proto:_hello_cc_proto_grpc_codegen' failed; build aborted
INFO: Elapsed time: 0.776s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

BUILD file contents:

```
package(default_visibility = ["//visibility:public"])

load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")

cc_grpc_library(
    name = "hello_cc_proto",
    srcs = ["hello.proto"],
    generate_mocks = True,
    proto_only = False,
    well_known_protos = False,
    deps = [],
)
```

bazel version results:

```
Bazelisk version: v1.0
Build label: 1.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:19:27 2019 (1570702767)
Build timestamp: 1570702767
Build timestamp as int: 1570702767
```

Already run `bazel clean --expunge` before build.

**Comment by coryan** [comment] 2019-10-14 12:57
@hcoona are you reporting a bug about google-cloud-cpp-spanner or with `gRPC`?  I do not see anything in your code that points to using this repository.

**Comment by coryan** [comment] 2019-10-14 12:59
FWIW, I just finished building with Bazel 1.0 on my mac:

```
$ ~/bin/bazel version
Build label: 1.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:19:27 2019 (1570702767)
Build timestamp: 1570702767
Build timestamp as int: 1570702767

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87

```

**Comment by coryan** [comment] 2019-10-14 13:14
There must be something that I am missing, because I cannot reproduce the problem. If you folks could produce more details I would be happy to try again, otherwise I will close this.

**Comment by coryan** [comment] 2019-10-15 12:43
Since all our CI builds have moved to Bazel 1.0 I am going to close this, please do reopen it if you have additional information.

**Closed by coryan** 2019-10-15 12:43 UTC
Labels: priority: p2, status: blocked, type: bug
